{% set name = "pubtator_loader" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pubtator_loader-{{ version }}.tar.gz
  sha256: 07460130ce81591c83f95a7cd6bd44c354cefc773ea978963283b54718a88abd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - spacy ==3.0.5

test:
  imports:
    - pubtator_loader
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/arshsekhon/pubtator_loader
  summary: Parse PubTator files with ease
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mbestipa
